// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"todo/ent/schema"
	"todo/ent/todoitem"
	"todo/ent/todolist"
	"todo/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoitemFields := schema.TodoItem{}.Fields()
	_ = todoitemFields
	// todoitemDescTitle is the schema descriptor for title field.
	todoitemDescTitle := todoitemFields[0].Descriptor()
	// todoitem.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	todoitem.TitleValidator = todoitemDescTitle.Validators[0].(func(string) error)
	// todoitemDescDone is the schema descriptor for done field.
	todoitemDescDone := todoitemFields[1].Descriptor()
	// todoitem.DefaultDone holds the default value on creation for the done field.
	todoitem.DefaultDone = todoitemDescDone.Default.(bool)
	// todoitemDescCreatedAt is the schema descriptor for created_at field.
	todoitemDescCreatedAt := todoitemFields[3].Descriptor()
	// todoitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	todoitem.DefaultCreatedAt = todoitemDescCreatedAt.Default.(time.Time)
	todolistFields := schema.TodoList{}.Fields()
	_ = todolistFields
	// todolistDescTitle is the schema descriptor for title field.
	todolistDescTitle := todolistFields[0].Descriptor()
	// todolist.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	todolist.TitleValidator = todolistDescTitle.Validators[0].(func(string) error)
	// todolistDescCreatedAt is the schema descriptor for created_at field.
	todolistDescCreatedAt := todolistFields[1].Descriptor()
	// todolist.DefaultCreatedAt holds the default value on creation for the created_at field.
	todolist.DefaultCreatedAt = todolistDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
