// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"todo/ent/predicate"
	"todo/ent/todoitem"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TodoItemDelete is the builder for deleting a TodoItem entity.
type TodoItemDelete struct {
	config
	hooks    []Hook
	mutation *TodoItemMutation
}

// Where appends a list predicates to the TodoItemDelete builder.
func (tid *TodoItemDelete) Where(ps ...predicate.TodoItem) *TodoItemDelete {
	tid.mutation.Where(ps...)
	return tid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tid *TodoItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tid.sqlExec, tid.mutation, tid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tid *TodoItemDelete) ExecX(ctx context.Context) int {
	n, err := tid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tid *TodoItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(todoitem.Table, sqlgraph.NewFieldSpec(todoitem.FieldID, field.TypeInt))
	if ps := tid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tid.mutation.done = true
	return affected, err
}

// TodoItemDeleteOne is the builder for deleting a single TodoItem entity.
type TodoItemDeleteOne struct {
	tid *TodoItemDelete
}

// Where appends a list predicates to the TodoItemDelete builder.
func (tido *TodoItemDeleteOne) Where(ps ...predicate.TodoItem) *TodoItemDeleteOne {
	tido.tid.mutation.Where(ps...)
	return tido
}

// Exec executes the deletion query.
func (tido *TodoItemDeleteOne) Exec(ctx context.Context) error {
	n, err := tido.tid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{todoitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tido *TodoItemDeleteOne) ExecX(ctx context.Context) {
	if err := tido.Exec(ctx); err != nil {
		panic(err)
	}
}
