// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"todo/ent/predicate"
	"todo/ent/todoitem"
	"todo/ent/todolist"
	"todo/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TodoListQuery is the builder for querying TodoList entities.
type TodoListQuery struct {
	config
	ctx        *QueryContext
	order      []todolist.OrderOption
	inters     []Interceptor
	predicates []predicate.TodoList
	withItems  *TodoItemQuery
	withUsers  *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TodoListQuery builder.
func (tlq *TodoListQuery) Where(ps ...predicate.TodoList) *TodoListQuery {
	tlq.predicates = append(tlq.predicates, ps...)
	return tlq
}

// Limit the number of records to be returned by this query.
func (tlq *TodoListQuery) Limit(limit int) *TodoListQuery {
	tlq.ctx.Limit = &limit
	return tlq
}

// Offset to start from.
func (tlq *TodoListQuery) Offset(offset int) *TodoListQuery {
	tlq.ctx.Offset = &offset
	return tlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tlq *TodoListQuery) Unique(unique bool) *TodoListQuery {
	tlq.ctx.Unique = &unique
	return tlq
}

// Order specifies how the records should be ordered.
func (tlq *TodoListQuery) Order(o ...todolist.OrderOption) *TodoListQuery {
	tlq.order = append(tlq.order, o...)
	return tlq
}

// QueryItems chains the current query on the "items" edge.
func (tlq *TodoListQuery) QueryItems() *TodoItemQuery {
	query := (&TodoItemClient{config: tlq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(todolist.Table, todolist.FieldID, selector),
			sqlgraph.To(todoitem.Table, todoitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, todolist.ItemsTable, todolist.ItemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(tlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsers chains the current query on the "users" edge.
func (tlq *TodoListQuery) QueryUsers() *UserQuery {
	query := (&UserClient{config: tlq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(todolist.Table, todolist.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, todolist.UsersTable, todolist.UsersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(tlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TodoList entity from the query.
// Returns a *NotFoundError when no TodoList was found.
func (tlq *TodoListQuery) First(ctx context.Context) (*TodoList, error) {
	nodes, err := tlq.Limit(1).All(setContextOp(ctx, tlq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{todolist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tlq *TodoListQuery) FirstX(ctx context.Context) *TodoList {
	node, err := tlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TodoList ID from the query.
// Returns a *NotFoundError when no TodoList ID was found.
func (tlq *TodoListQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tlq.Limit(1).IDs(setContextOp(ctx, tlq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{todolist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tlq *TodoListQuery) FirstIDX(ctx context.Context) int {
	id, err := tlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TodoList entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TodoList entity is found.
// Returns a *NotFoundError when no TodoList entities are found.
func (tlq *TodoListQuery) Only(ctx context.Context) (*TodoList, error) {
	nodes, err := tlq.Limit(2).All(setContextOp(ctx, tlq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{todolist.Label}
	default:
		return nil, &NotSingularError{todolist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tlq *TodoListQuery) OnlyX(ctx context.Context) *TodoList {
	node, err := tlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TodoList ID in the query.
// Returns a *NotSingularError when more than one TodoList ID is found.
// Returns a *NotFoundError when no entities are found.
func (tlq *TodoListQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tlq.Limit(2).IDs(setContextOp(ctx, tlq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{todolist.Label}
	default:
		err = &NotSingularError{todolist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tlq *TodoListQuery) OnlyIDX(ctx context.Context) int {
	id, err := tlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TodoLists.
func (tlq *TodoListQuery) All(ctx context.Context) ([]*TodoList, error) {
	ctx = setContextOp(ctx, tlq.ctx, "All")
	if err := tlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TodoList, *TodoListQuery]()
	return withInterceptors[[]*TodoList](ctx, tlq, qr, tlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tlq *TodoListQuery) AllX(ctx context.Context) []*TodoList {
	nodes, err := tlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TodoList IDs.
func (tlq *TodoListQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tlq.ctx.Unique == nil && tlq.path != nil {
		tlq.Unique(true)
	}
	ctx = setContextOp(ctx, tlq.ctx, "IDs")
	if err = tlq.Select(todolist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tlq *TodoListQuery) IDsX(ctx context.Context) []int {
	ids, err := tlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tlq *TodoListQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tlq.ctx, "Count")
	if err := tlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tlq, querierCount[*TodoListQuery](), tlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tlq *TodoListQuery) CountX(ctx context.Context) int {
	count, err := tlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tlq *TodoListQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tlq.ctx, "Exist")
	switch _, err := tlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tlq *TodoListQuery) ExistX(ctx context.Context) bool {
	exist, err := tlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TodoListQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tlq *TodoListQuery) Clone() *TodoListQuery {
	if tlq == nil {
		return nil
	}
	return &TodoListQuery{
		config:     tlq.config,
		ctx:        tlq.ctx.Clone(),
		order:      append([]todolist.OrderOption{}, tlq.order...),
		inters:     append([]Interceptor{}, tlq.inters...),
		predicates: append([]predicate.TodoList{}, tlq.predicates...),
		withItems:  tlq.withItems.Clone(),
		withUsers:  tlq.withUsers.Clone(),
		// clone intermediate query.
		sql:  tlq.sql.Clone(),
		path: tlq.path,
	}
}

// WithItems tells the query-builder to eager-load the nodes that are connected to
// the "items" edge. The optional arguments are used to configure the query builder of the edge.
func (tlq *TodoListQuery) WithItems(opts ...func(*TodoItemQuery)) *TodoListQuery {
	query := (&TodoItemClient{config: tlq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tlq.withItems = query
	return tlq
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (tlq *TodoListQuery) WithUsers(opts ...func(*UserQuery)) *TodoListQuery {
	query := (&UserClient{config: tlq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tlq.withUsers = query
	return tlq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TodoList.Query().
//		GroupBy(todolist.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tlq *TodoListQuery) GroupBy(field string, fields ...string) *TodoListGroupBy {
	tlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TodoListGroupBy{build: tlq}
	grbuild.flds = &tlq.ctx.Fields
	grbuild.label = todolist.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.TodoList.Query().
//		Select(todolist.FieldTitle).
//		Scan(ctx, &v)
func (tlq *TodoListQuery) Select(fields ...string) *TodoListSelect {
	tlq.ctx.Fields = append(tlq.ctx.Fields, fields...)
	sbuild := &TodoListSelect{TodoListQuery: tlq}
	sbuild.label = todolist.Label
	sbuild.flds, sbuild.scan = &tlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TodoListSelect configured with the given aggregations.
func (tlq *TodoListQuery) Aggregate(fns ...AggregateFunc) *TodoListSelect {
	return tlq.Select().Aggregate(fns...)
}

func (tlq *TodoListQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tlq); err != nil {
				return err
			}
		}
	}
	for _, f := range tlq.ctx.Fields {
		if !todolist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tlq.path != nil {
		prev, err := tlq.path(ctx)
		if err != nil {
			return err
		}
		tlq.sql = prev
	}
	return nil
}

func (tlq *TodoListQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TodoList, error) {
	var (
		nodes       = []*TodoList{}
		_spec       = tlq.querySpec()
		loadedTypes = [2]bool{
			tlq.withItems != nil,
			tlq.withUsers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TodoList).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TodoList{config: tlq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tlq.withItems; query != nil {
		if err := tlq.loadItems(ctx, query, nodes,
			func(n *TodoList) { n.Edges.Items = []*TodoItem{} },
			func(n *TodoList, e *TodoItem) { n.Edges.Items = append(n.Edges.Items, e) }); err != nil {
			return nil, err
		}
	}
	if query := tlq.withUsers; query != nil {
		if err := tlq.loadUsers(ctx, query, nodes,
			func(n *TodoList) { n.Edges.Users = []*User{} },
			func(n *TodoList, e *User) { n.Edges.Users = append(n.Edges.Users, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tlq *TodoListQuery) loadItems(ctx context.Context, query *TodoItemQuery, nodes []*TodoList, init func(*TodoList), assign func(*TodoList, *TodoItem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*TodoList)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.TodoItem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(todolist.ItemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.todo_list_items
		if fk == nil {
			return fmt.Errorf(`foreign-key "todo_list_items" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "todo_list_items" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (tlq *TodoListQuery) loadUsers(ctx context.Context, query *UserQuery, nodes []*TodoList, init func(*TodoList), assign func(*TodoList, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*TodoList)
	nids := make(map[int]map[*TodoList]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(todolist.UsersTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(todolist.UsersPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(todolist.UsersPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(todolist.UsersPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*TodoList]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*User](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "users" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (tlq *TodoListQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tlq.querySpec()
	_spec.Node.Columns = tlq.ctx.Fields
	if len(tlq.ctx.Fields) > 0 {
		_spec.Unique = tlq.ctx.Unique != nil && *tlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tlq.driver, _spec)
}

func (tlq *TodoListQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(todolist.Table, todolist.Columns, sqlgraph.NewFieldSpec(todolist.FieldID, field.TypeInt))
	_spec.From = tlq.sql
	if unique := tlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tlq.path != nil {
		_spec.Unique = true
	}
	if fields := tlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todolist.FieldID)
		for i := range fields {
			if fields[i] != todolist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tlq *TodoListQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tlq.driver.Dialect())
	t1 := builder.Table(todolist.Table)
	columns := tlq.ctx.Fields
	if len(columns) == 0 {
		columns = todolist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tlq.sql != nil {
		selector = tlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tlq.ctx.Unique != nil && *tlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tlq.predicates {
		p(selector)
	}
	for _, p := range tlq.order {
		p(selector)
	}
	if offset := tlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TodoListGroupBy is the group-by builder for TodoList entities.
type TodoListGroupBy struct {
	selector
	build *TodoListQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tlgb *TodoListGroupBy) Aggregate(fns ...AggregateFunc) *TodoListGroupBy {
	tlgb.fns = append(tlgb.fns, fns...)
	return tlgb
}

// Scan applies the selector query and scans the result into the given value.
func (tlgb *TodoListGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tlgb.build.ctx, "GroupBy")
	if err := tlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TodoListQuery, *TodoListGroupBy](ctx, tlgb.build, tlgb, tlgb.build.inters, v)
}

func (tlgb *TodoListGroupBy) sqlScan(ctx context.Context, root *TodoListQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tlgb.fns))
	for _, fn := range tlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tlgb.flds)+len(tlgb.fns))
		for _, f := range *tlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TodoListSelect is the builder for selecting fields of TodoList entities.
type TodoListSelect struct {
	*TodoListQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tls *TodoListSelect) Aggregate(fns ...AggregateFunc) *TodoListSelect {
	tls.fns = append(tls.fns, fns...)
	return tls
}

// Scan applies the selector query and scans the result into the given value.
func (tls *TodoListSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tls.ctx, "Select")
	if err := tls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TodoListQuery, *TodoListSelect](ctx, tls.TodoListQuery, tls, tls.inters, v)
}

func (tls *TodoListSelect) sqlScan(ctx context.Context, root *TodoListQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tls.fns))
	for _, fn := range tls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
