// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"todo/ent/predicate"
	"todo/ent/todoitem"
	"todo/ent/todolist"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TodoItemQuery is the builder for querying TodoItem entities.
type TodoItemQuery struct {
	config
	ctx        *QueryContext
	order      []todoitem.OrderOption
	inters     []Interceptor
	predicates []predicate.TodoItem
	withList   *TodoListQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TodoItemQuery builder.
func (tiq *TodoItemQuery) Where(ps ...predicate.TodoItem) *TodoItemQuery {
	tiq.predicates = append(tiq.predicates, ps...)
	return tiq
}

// Limit the number of records to be returned by this query.
func (tiq *TodoItemQuery) Limit(limit int) *TodoItemQuery {
	tiq.ctx.Limit = &limit
	return tiq
}

// Offset to start from.
func (tiq *TodoItemQuery) Offset(offset int) *TodoItemQuery {
	tiq.ctx.Offset = &offset
	return tiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tiq *TodoItemQuery) Unique(unique bool) *TodoItemQuery {
	tiq.ctx.Unique = &unique
	return tiq
}

// Order specifies how the records should be ordered.
func (tiq *TodoItemQuery) Order(o ...todoitem.OrderOption) *TodoItemQuery {
	tiq.order = append(tiq.order, o...)
	return tiq
}

// QueryList chains the current query on the "list" edge.
func (tiq *TodoItemQuery) QueryList() *TodoListQuery {
	query := (&TodoListClient{config: tiq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(todoitem.Table, todoitem.FieldID, selector),
			sqlgraph.To(todolist.Table, todolist.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, todoitem.ListTable, todoitem.ListColumn),
		)
		fromU = sqlgraph.SetNeighbors(tiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TodoItem entity from the query.
// Returns a *NotFoundError when no TodoItem was found.
func (tiq *TodoItemQuery) First(ctx context.Context) (*TodoItem, error) {
	nodes, err := tiq.Limit(1).All(setContextOp(ctx, tiq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{todoitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tiq *TodoItemQuery) FirstX(ctx context.Context) *TodoItem {
	node, err := tiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TodoItem ID from the query.
// Returns a *NotFoundError when no TodoItem ID was found.
func (tiq *TodoItemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tiq.Limit(1).IDs(setContextOp(ctx, tiq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{todoitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tiq *TodoItemQuery) FirstIDX(ctx context.Context) int {
	id, err := tiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TodoItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TodoItem entity is found.
// Returns a *NotFoundError when no TodoItem entities are found.
func (tiq *TodoItemQuery) Only(ctx context.Context) (*TodoItem, error) {
	nodes, err := tiq.Limit(2).All(setContextOp(ctx, tiq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{todoitem.Label}
	default:
		return nil, &NotSingularError{todoitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tiq *TodoItemQuery) OnlyX(ctx context.Context) *TodoItem {
	node, err := tiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TodoItem ID in the query.
// Returns a *NotSingularError when more than one TodoItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (tiq *TodoItemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tiq.Limit(2).IDs(setContextOp(ctx, tiq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{todoitem.Label}
	default:
		err = &NotSingularError{todoitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tiq *TodoItemQuery) OnlyIDX(ctx context.Context) int {
	id, err := tiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TodoItems.
func (tiq *TodoItemQuery) All(ctx context.Context) ([]*TodoItem, error) {
	ctx = setContextOp(ctx, tiq.ctx, "All")
	if err := tiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TodoItem, *TodoItemQuery]()
	return withInterceptors[[]*TodoItem](ctx, tiq, qr, tiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tiq *TodoItemQuery) AllX(ctx context.Context) []*TodoItem {
	nodes, err := tiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TodoItem IDs.
func (tiq *TodoItemQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tiq.ctx.Unique == nil && tiq.path != nil {
		tiq.Unique(true)
	}
	ctx = setContextOp(ctx, tiq.ctx, "IDs")
	if err = tiq.Select(todoitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tiq *TodoItemQuery) IDsX(ctx context.Context) []int {
	ids, err := tiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tiq *TodoItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tiq.ctx, "Count")
	if err := tiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tiq, querierCount[*TodoItemQuery](), tiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tiq *TodoItemQuery) CountX(ctx context.Context) int {
	count, err := tiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tiq *TodoItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tiq.ctx, "Exist")
	switch _, err := tiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tiq *TodoItemQuery) ExistX(ctx context.Context) bool {
	exist, err := tiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TodoItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tiq *TodoItemQuery) Clone() *TodoItemQuery {
	if tiq == nil {
		return nil
	}
	return &TodoItemQuery{
		config:     tiq.config,
		ctx:        tiq.ctx.Clone(),
		order:      append([]todoitem.OrderOption{}, tiq.order...),
		inters:     append([]Interceptor{}, tiq.inters...),
		predicates: append([]predicate.TodoItem{}, tiq.predicates...),
		withList:   tiq.withList.Clone(),
		// clone intermediate query.
		sql:  tiq.sql.Clone(),
		path: tiq.path,
	}
}

// WithList tells the query-builder to eager-load the nodes that are connected to
// the "list" edge. The optional arguments are used to configure the query builder of the edge.
func (tiq *TodoItemQuery) WithList(opts ...func(*TodoListQuery)) *TodoItemQuery {
	query := (&TodoListClient{config: tiq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tiq.withList = query
	return tiq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TodoItem.Query().
//		GroupBy(todoitem.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tiq *TodoItemQuery) GroupBy(field string, fields ...string) *TodoItemGroupBy {
	tiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TodoItemGroupBy{build: tiq}
	grbuild.flds = &tiq.ctx.Fields
	grbuild.label = todoitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.TodoItem.Query().
//		Select(todoitem.FieldTitle).
//		Scan(ctx, &v)
func (tiq *TodoItemQuery) Select(fields ...string) *TodoItemSelect {
	tiq.ctx.Fields = append(tiq.ctx.Fields, fields...)
	sbuild := &TodoItemSelect{TodoItemQuery: tiq}
	sbuild.label = todoitem.Label
	sbuild.flds, sbuild.scan = &tiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TodoItemSelect configured with the given aggregations.
func (tiq *TodoItemQuery) Aggregate(fns ...AggregateFunc) *TodoItemSelect {
	return tiq.Select().Aggregate(fns...)
}

func (tiq *TodoItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tiq); err != nil {
				return err
			}
		}
	}
	for _, f := range tiq.ctx.Fields {
		if !todoitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tiq.path != nil {
		prev, err := tiq.path(ctx)
		if err != nil {
			return err
		}
		tiq.sql = prev
	}
	return nil
}

func (tiq *TodoItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TodoItem, error) {
	var (
		nodes       = []*TodoItem{}
		withFKs     = tiq.withFKs
		_spec       = tiq.querySpec()
		loadedTypes = [1]bool{
			tiq.withList != nil,
		}
	)
	if tiq.withList != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, todoitem.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TodoItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TodoItem{config: tiq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tiq.withList; query != nil {
		if err := tiq.loadList(ctx, query, nodes, nil,
			func(n *TodoItem, e *TodoList) { n.Edges.List = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tiq *TodoItemQuery) loadList(ctx context.Context, query *TodoListQuery, nodes []*TodoItem, init func(*TodoItem), assign func(*TodoItem, *TodoList)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*TodoItem)
	for i := range nodes {
		if nodes[i].todo_list_items == nil {
			continue
		}
		fk := *nodes[i].todo_list_items
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(todolist.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "todo_list_items" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tiq *TodoItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tiq.querySpec()
	_spec.Node.Columns = tiq.ctx.Fields
	if len(tiq.ctx.Fields) > 0 {
		_spec.Unique = tiq.ctx.Unique != nil && *tiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tiq.driver, _spec)
}

func (tiq *TodoItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(todoitem.Table, todoitem.Columns, sqlgraph.NewFieldSpec(todoitem.FieldID, field.TypeInt))
	_spec.From = tiq.sql
	if unique := tiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tiq.path != nil {
		_spec.Unique = true
	}
	if fields := tiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todoitem.FieldID)
		for i := range fields {
			if fields[i] != todoitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tiq *TodoItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tiq.driver.Dialect())
	t1 := builder.Table(todoitem.Table)
	columns := tiq.ctx.Fields
	if len(columns) == 0 {
		columns = todoitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tiq.sql != nil {
		selector = tiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tiq.ctx.Unique != nil && *tiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tiq.predicates {
		p(selector)
	}
	for _, p := range tiq.order {
		p(selector)
	}
	if offset := tiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TodoItemGroupBy is the group-by builder for TodoItem entities.
type TodoItemGroupBy struct {
	selector
	build *TodoItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tigb *TodoItemGroupBy) Aggregate(fns ...AggregateFunc) *TodoItemGroupBy {
	tigb.fns = append(tigb.fns, fns...)
	return tigb
}

// Scan applies the selector query and scans the result into the given value.
func (tigb *TodoItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tigb.build.ctx, "GroupBy")
	if err := tigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TodoItemQuery, *TodoItemGroupBy](ctx, tigb.build, tigb, tigb.build.inters, v)
}

func (tigb *TodoItemGroupBy) sqlScan(ctx context.Context, root *TodoItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tigb.fns))
	for _, fn := range tigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tigb.flds)+len(tigb.fns))
		for _, f := range *tigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TodoItemSelect is the builder for selecting fields of TodoItem entities.
type TodoItemSelect struct {
	*TodoItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tis *TodoItemSelect) Aggregate(fns ...AggregateFunc) *TodoItemSelect {
	tis.fns = append(tis.fns, fns...)
	return tis
}

// Scan applies the selector query and scans the result into the given value.
func (tis *TodoItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tis.ctx, "Select")
	if err := tis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TodoItemQuery, *TodoItemSelect](ctx, tis.TodoItemQuery, tis, tis.inters, v)
}

func (tis *TodoItemSelect) sqlScan(ctx context.Context, root *TodoItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tis.fns))
	for _, fn := range tis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
