// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TodoItem is the predicate function for todoitem builders.
type TodoItem func(*sql.Selector)

// TodoList is the predicate function for todolist builders.
type TodoList func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
